frostwire/frostwire

- android/src/com/frostwire/android/gui/adapters/menu/SendBitcoinTipAction.java
- android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
- android/src/com/frostwire/android/gui/transfers/HttpDownload.java
- android/src/com/frostwire/android/gui/transfers/YouTubeDownload.java
- desktop/src/com/limegroup/gnutella/gui/options/panes/SearchEnginesPaneItem.java
- desktop/src/com/limegroup/gnutella/gui/shell/FileTypeAssociation.java
(did not correctly rebase, but it feels good)
(nothing to do with tip4commit. just finally had time)
> small fixes

- android/AndroidManifest.xml
- android/apollo/src/com/andrew/apollo/ui/activities/BaseActivity.java
The icon would disappear after exiting the search on Apollo.
> [android] fixed homeAsUpIndicator disappearing after search

- android/res/drawable/wizard_button_off.xml
- android/res/drawable/wizard_button_on.xml
- android/res/drawable/wizard_button_selector.xml
- android/res/layout/activity_wizard.xml
- android/res/layout/view_general_wizard_page.xml
- android/res/layout/view_intent_wizard_page.xml
- android/res/values/strings.xml
- android/res/values/styles.xml
Still needs work. Current Storage Location is not functional yet, just a dummy text. 
Also the "Seed only on Wifi" should be fully unchecked while 'Seed Finished Torrents" is also unchecked. 
As of now it still looks like seed only on wifi is preselected for the user and a default action.
> Wizard page update

- README.md
Updated Readme file for clarification.
> Noticed that both use same license

- README.md
Changed pollude to pollute as I don't think pollude is a word.
> Update README.md Minor Spelling Error

- android/README.md
Minor Grammatical error corrected, added a comma in after "when you submit your pull request"
> Update README.md, Minor Grammatical Mistake Corrected

- android/README.md
Changed position of it to make sense and added a comma to make the text read better.
> Small sentence error corrected in line 23

- desktop/lib/messagebundles/pt.po
First update. I'm working on this translation. A lot of errors.
> [desktop] Portuguese Translation Update

- desktop/lib/messagebundles/fr.po
I edited some mistakes, and mistranslated lines. Anyway we need a native French speaker to review the translation thoroughly.
> [desktop] French Translation Update 1.

- desktop/lib/messagebundles/pt_BR.po
I edited many phrases that make no sense.
> [desktop] Portuguese-Brazil Translation Update 1.

- desktop/lib/messagebundles/it.po
I edit some lines because there were erroneous translations. Again, if there is any italian native speaker reading this, please check the translation :).
> [desktop] Italian Translation Update 1.

- android/build.gradle
- android/tests/espresso/com/frostwire/android/gui/activities/FirstLaunchTest.java
- android/tests/espresso/com/frostwire/android/test/utils/PreferencesManipulator.java
- android/tests/espresso/com/frostwire/android/test/utils/WaitUntiVisibleIdlingResource.java
This test "FirstLaunchTest" check the 'next' buttons on dialogues to install the app:
Ref. I-2	Open FrostWire and accept terms and conditions
Ref. I-3	Welcome FrostWire - Wizard (only 'Next' button)
Ref. I-4	Check box 'copyright infringement' and 'Finish'
Ref. I-5    Click 'ok' Social pages pop-up
> First Test on espresso-2 branch

- android/apollo/src/com/andrew/apollo/adapters/ProfileSongAdapter.java
- android/apollo/src/com/andrew/apollo/ui/fragments/profile/PlaylistSongFragment.java
Everything was "ok" in the View. The problem lay with no listener that would change the adapter (and data in system). The problem with the adapter is that it uses a copy of the data other than the one in ArryAdaper (why? 0.o) so that copy also has to be updated.
> [android] issue #116 repositioning songs in playlist

- android/apollo/src/com/andrew/apollo/adapters/ProfileSongAdapter.java
- android/apollo/src/com/andrew/apollo/ui/fragments/profile/PlaylistSongFragment.java
same as pull request #136 but from a new branch and with double list modification inside a critical section
> [android] issue #116 repositioning songs in playlist - new branch

- common/src/main/java/com/frostwire/util/http/OKHTTPClient.java
I kept getting the following error after making a few searches while fixing a bug on EZTV.
I've had this issue in the past, and what happens when you start seeing this, is that FrostWire simply doesn't connect to any search engine, as it seems the HTTP client is exhausted.
I believe you mentioned something related to this earlier this week but you know my memory.
In any case I searched for the error and the brain took me [to this conversation on OKHttp](https://github.com/square/okhttp/issues/2158) which lead to [this documentation update](https://github.com/square/okhttp/pull/2159/files#diff-8293e59e7aba0f85474c4ad7a639a4c7R35) on `ResponseBody`.
On this patch I tried to make sure that every `ResponseBody` object created was closed quietly.
I've not been able to replicate the error so …
> [common] avoid connection leaks with OKHttpClient.

- android/res/layout/dialog_default_update.xml
The buttons of the Update Dialog we invisible when more bullet points were used - pushing them down. Switched the layout to relativelayout.
> [android] fix for hidden update dialog buttons

- desktop/changelog
Hi!
When I open frostwire, I get a pop up window telling me:
```
I have downloaded the newest FrostWire for you
-Fixes YT search issues.
-Fixes freeze issues.
Would you like to install it now?
```
When I click "yes", my package manager opens and installation fails with this log
```
E: frostwire: arch-independent-package-contains-binary-or-object usr/lib/frostwire/libjlibtorrent.so
E: frostwire: embedded-library usr/lib/frostwire/libjlibtorrent.so: openssl
E: frostwire: arch-independent-package-contains-binary-or-object usr/lib/frostwire/libjlibtorrentx86.so
E: frostwire: embedded-library usr/lib/frostwire/libjlibtorrentx86.so: openssl
W: frostwire: syntax-error-in-debian-changelog line 165 "no se ha podido interpretar la fecha Aug, 14 Jul 2015 16:15:00 -0500"
W: frostwire: …
```
> Debian installation

- android/res/drawable/activity_buy_interstitial_ad_free_button_background.xml
- android/res/layout/activity_buy.xml
- android/res/values/styles.xml
Small final adjustments: 
Adjusted padding so that the ad is fully visible on smaller screens, the last part was cut on some hdpi devices.
Adjusted colors of the ad-free border and text.
> [android] adjusted paddings and colors

- android/AndroidManifest.xml
- android/apollo/src/com/andrew/apollo/MusicPlaybackService.java
- android/apollo/src/com/andrew/apollo/ui/fragments/PlaylistFragment.java
- android/build.gradle
- android/res/layout/view_main_fragment_simple_header.xml
- android/src/com/frostwire/android/core/ConfigurationDefaults.java
- android/src/com/frostwire/android/core/ConfigurationManager.java
- android/src/com/frostwire/android/core/Constants.java
- android/src/com/frostwire/android/gui/SoftwareUpdater.java
- android/src/com/frostwire/android/gui/activities/BuyActivity.java
- android/src/com/frostwire/android/gui/activities/MainActivity.java
- android/src/com/frostwire/android/gui/adapters/menu/SeedAction.java
- android/src/com/frostwire/android/gui/dialogs/YouTubeDownloadDialog.java
- android/src/com/frostwire/android/gui/fragments/SearchFragment.java
- android/src/com/frostwire/android/gui/services/Engine.java
- android/src/com/frostwire/android/gui/views/SearchInputView.java
- android/src/com/frostwire/android/offers/AdNetwork.java
- android/src/com/frostwire/android/offers/AppLovinAdNetwork.java
- android/src/com/frostwire/android/offers/AppLovinInterstitialAdapter.java
- android/src/com/frostwire/android/offers/InMobiAdNetwork.java
- android/src/com/frostwire/android/offers/InMobiInterstitialListener.java
- android/src/com/frostwire/android/offers/InterstitialListener.java
- android/src/com/frostwire/android/offers/MobFoxAdNetwork.java
- android/src/com/frostwire/android/offers/MobFoxInterstitialListener.java
- android/src/com/frostwire/android/offers/Offers.java
- android/src/com/frostwire/android/offers/RemoveAdsNetwork.java
- android/src/com/frostwire/android/util/SystemUtils.java
closed older PR, reopening after rebase. few more fixes and tests pending after this rebase.
> Mobfox (rebased)

- desktop/src/com/frostwire/gui/bittorrent/BTDownloadActions.java
- desktop/src/com/frostwire/gui/bittorrent/BittorrentDownload.java
- desktop/src/com/frostwire/gui/bittorrent/ShareTorrentDialog.java
- desktop/src/com/frostwire/gui/bittorrent/TorrentUtil.java
This pull request is intended to solve #170 .
> [desktop] Adding Main app frame as parameter to ShareTorrentDialog constructor

- android/res/values-pl/strings.xml
> Polish translation update correction

- android/AndroidManifest.xml
- android/apollo/res/layout-land/activity_player_base.xml
- android/apollo/res/layout/activity_player_base.xml
- android/apollo/res/values-pt-rBR/strings.xml
- android/apollo/res/values-pt-rPT/strings.xml
- android/apollo/src/com/andrew/apollo/ui/activities/AudioPlayerActivity.java
- android/apollo/src/com/andrew/apollo/utils/MusicUtils.java
- android/apollo/src/com/andrew/apollo/widgets/RepeatingImageButton.java
- android/apollo/src/com/andrew/apollo/widgets/theme/ThemeableFrameLayout.java
- android/apollo/src/com/andrew/apollo/widgets/theme/ThemeableSeekBar.java
- android/build.gradle
- android/changelog.txt
- android/res/values-de/strings.xml
- android/res/values-el/strings.xml
- android/res/values-es/strings.xml
- android/res/values-fr/strings.xml
- android/res/values-nl/strings.xml
- android/res/values-pl/strings.xml
- android/res/values-pt/strings.xml
- android/res/values-ru/strings.xml
- android/res/values-zh/strings.xml
- android/res/values/strings.xml
- android/src/com/frostwire/android/core/ConfigurationDefaults.java
- android/src/com/frostwire/android/core/Constants.java
- android/src/com/frostwire/android/gui/SoftwareUpdater.java
- android/src/com/frostwire/android/gui/activities/BuyActivity.java
- android/src/com/frostwire/android/gui/activities/SettingsActivity.java
- android/src/com/frostwire/android/offers/Offers.java
Very very WIP, just started the PR so I can easily keep track of all the files that have changed so far.
> [WIP] Mopub

- android/apollo/src/com/andrew/apollo/IApolloService.aidl
- android/apollo/src/com/andrew/apollo/MusicPlaybackService.java
- android/apollo/src/com/andrew/apollo/utils/MusicUtils.java
- android/src/com/frostwire/android/core/player/CoreMediaPlayer.java
- android/src/com/frostwire/android/gui/adapters/menu/FileListAdapter.java
- android/src/com/frostwire/android/gui/adapters/menu/OpenMenuAction.java
- android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
- android/src/com/frostwire/android/gui/services/ApolloMediaPlayer.java
- android/src/com/frostwire/android/gui/views/AbstractListAdapter.java
- android/src/com/frostwire/android/gui/views/BrowsePeerSearchBarView.java
- android/src/com/frostwire/android/gui/views/BrowseThumbnailImageButton.java
this fixes
#225
#226
#233 (actually that is just a one line fix in the BrowseThumbnailImageButton and was needed in the above issues anyway)
> [android] Issues with ringtone playback (#225, #226, #233)

- android/apollo/src/com/andrew/apollo/ui/activities/ProfileActivity.java
- android/apollo/src/com/andrew/apollo/utils/ApolloUtils.java
As per @aldenml request making this part separate
> [android] moving creation of shortcut on home screen to asynchronous task

- desktop/src/com/frostwire/gui/library/LibraryExplorer.java
- desktop/src/com/frostwire/gui/library/LibraryPlaylists.java
- desktop/src/com/limegroup/gnutella/settings/UISettings.java
This pull request is intended to solve issue #182
> [desktop] Move 'Starred' list within Playlist section  #182

- android/AndroidManifest.xml
- android/res/layout/activity_buy_products.xml
- android/src/com/frostwire/android/gui/activities/BuyActivity.java
Don't want to change any styles yet. Just wanted to extend AbstractActivity2 and set up a new toolbar. Let me know if its ok. 
Removed toolbar when in InterstitialMode.
> [android] adding material theme to BuyActivity.

- android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
> [android/#285] Small file list bugs - RELOADED

- android/res/values/strings.xml
- android/res/xml/settings_application.xml
- android/res/xml/settings_other.xml
- android/res/xml/settings_search.xml
- android/res/xml/settings_torrent.xml
- android/src/com/frostwire/android/gui/activities/SettingsActivity2.java
@aldenml Just added all the preferences in the discussed order.
Plan of action:
1) adjust some few remaining custom layouts we use for preferences, add new styles
2) work on making preferences functional ( with @grzesiekrzaca ):
a) BitTorrent connection, Wifi networks only, Select Storage
b) Toggle state and search settings
c) Torrent preferences
d) Other
3) work on the single and double pane view of settings based on screen size
> [android] added all preferences to the newly created settings activity

- android/res/layout/view_product_card.xml
- android/res/values/styles.xml
- android/src/com/frostwire/android/gui/views/ProductCardView.java
Changed just few styles for now - for better readability, simplified view_product_card layout.
> Remove ads design update

- android/res/values/styles.xml
> [android] fixed BuyNoAds font style

- android/res/values/themes.xml
@aldenml thank you for that suggestion, works perfectly on my phones and all emulators. Including API18, 23 and 25 tablets.
> [android] added list item padding to FW theme

- android/res/values/strings.xml
- android/res/xml/settings_search.xml
old strings can be deleted after removing application_preferences
> [android] updated preference summary strings

- android/res/drawable/clearable_edittext_background.xml
- android/res/layout/view_searchinput.xml
The white search input was not visible on the white background
> [android] added missing background to the search input

- android/res/layout/view_preference_search_engine.xml
- android/res/values/colors.xml
- android/res/values/strings.xml
- android/res/xml/settings_search.xml
- android/src/com/frostwire/android/gui/activities/SettingsActivity.java
- android/src/com/frostwire/android/gui/fragments/preference/SearchFragment.java
> [android] select all ux changes

- android/res/layout/activity_main.xml
- android/src/com/frostwire/android/gui/activities/MainActivity.java
snackbar is now appearing on top of the android bottom nav, works
> [android] added linearlayout anchor for the bittorrent snackbar

- desktop/src/com/limegroup/gnutella/gui/VPNDropGuard.java
resume call instead of stop, wait, start.
> [android] resume instead of restart of changing the option

- desktop/src/com/frostwire/gui/bittorrent/CreateTorrentDialog.java
Added piece size selector for create torrent window.
> [desktop] Added piece size selector for create torrent window

- android/res/layout-land/nav_view_header.xml
- android/res/layout/nav_view_header.xml
Left by mistake while testing. Sorry.
> [android] removed unnecessary visiblity option

- android/res/layout/fragment_browse_peer.xml
- android/res/layout/view_preference_search_select_all.xml
- android/res/values/styles.xml
- android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
Styled the 'select/deselect all' container, removed unnecessary RadioButton spacer.
> [android] styled select/deselect all container

- android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
Worked well. Thank you @gubatron
> [android] fixes UI when deleting files in selection mode

- android/AndroidManifest.xml
- android/res/layout/activity_wizard.xml
- android/res/layout/view_general_wizard_page.xml
Instead of new wizard, scroll view will do good.
> [android] made the wizard page scrollable in horizontal mode

- android/res/layout/dialog_default_update.xml
ListView was only set to appear below a TextView but a lower boundary was not set. Added android:layout_above="@+id/dialog_default_update_buttons" to set that boundary. Fixed issue on my phone.
> [android] fixed update message buttons overlaying the listview

- android/res/layout/view_intent_wizard_page.xml
Enables scrolling on small screen devices. The first wizard page was already inside the ScrollView.
> [android] added missing ScrollView to intent wizard page

- android/res/values-pl/strings.xml
> [android] Polish translation updated

- android/res/layout/fragment_transfers.xml
Now the tabs extend the width of the device on tablet.
> [android] fixed horizontal positioning of the transfer tabs on tablet

- android/res/menu/nav_view_menu.xml
the text was not getting translated
> [android] fixed left hard coded strings

- android/res/layout-land/view_searchinput_tablayout.xml
- android/res/layout-land/view_searchinput_tablayout_custom_tab.xml
- android/res/layout/view_transfers_header.xml
- android/res/menu/fragment_transfers_menu.xml
- android/res/values/strings.xml
- android/src/com/frostwire/android/gui/fragments/TransfersFragment.java
> Transfers toolbar update

- android/apollo/res/layout/fragment_music_browser_phone.xml
- android/apollo/res/layout/new_playlist_list_item.xml
- android/apollo/src/com/andrew/apollo/adapters/PlaylistAdapter.java
- android/apollo/src/com/andrew/apollo/loaders/PlaylistLoader.java
- android/apollo/src/com/andrew/apollo/ui/fragments/PlaylistFragment.java
- android/res/layout/view_toolbar_title_subtitle_header.xml
@gubatron worked well. Thanks. 
I separated all my other list ui updates, so this branch only focuses on updating playlists.
> Apollo playlist ui update

- android/apollo/res/layout/new_playlist_list_item.xml
@gubatron yes, stupid mistake. Sorry. Thank you for noticing.
> [android] updated the ids in new_playlist_list_item layout

- android/res/drawable/keyword_tag_background_tip_active.xml
- android/res/layout/view_drawer_search_filters.xml
- android/res/values/colors.xml
- android/res/values/strings.xml
- android/res/values/styles.xml
- android/src/com/frostwire/android/core/ConfigurationDefaults.java
- android/src/com/frostwire/android/core/Constants.java
- android/src/com/frostwire/android/gui/views/KeywordFilterDrawerView.java
DO NOT Merge yet :)
@gubatron 
Left to do: connect the dismiss button so that the tip does not shows after a user dismissed it.
I will work on colors a bit later, I think they can be improved.
> Added updated include exclude tip

- android/res/layout/view_search_header_banner.xml
- android/res/values/strings.xml
If you like it here are the changes - email sent.
> [android] small style/layout changes to header_banner

- android/src/com/frostwire/android/gui/activities/MainActivity.java
- android/src/com/frostwire/android/gui/adapters/TransferListAdapter.java
- android/src/com/frostwire/android/gui/adapters/menu/CancelMenuAction.java
- android/src/com/frostwire/android/gui/dialogs/HandpickedTorrentDownloadDialog.java
- android/src/com/frostwire/android/gui/dialogs/HandpickedTorrentDownloadDialogOnFetch.java
- android/src/com/frostwire/android/gui/fragments/TransfersFragment.java
- android/src/com/frostwire/android/gui/tasks/StartDownloadTask.java
- android/src/com/frostwire/android/gui/transfers/TorrentFetcherDownload.java
- android/src/com/frostwire/android/gui/transfers/TorrentFetcherListener.java
- android/src/com/frostwire/android/gui/transfers/TorrentUrlInfo.java
- android/src/com/frostwire/android/gui/transfers/TransferManager.java
Also, when transfers are removed the transfer list is now refreshed immediatly.
> [android] issue 594, shows transfer while fetching torrent

- desktop/src/com/limegroup/gnutella/gui/menu/HelpMenu.java
1) Removed:
- Order Frostwire Stickers
- Frostwire T-Shirts
2) Added : 
- Support Frostwire links to http://www.frostwire.com/give
3) Updated:
- Frostwire Forums links to http://forum.frostwire.com/
> [desktop] Help Menu links maintenance (#633)

- android/res/values/strings.xml
Changed the text in order for the buttons to be visible above the fold.
> [android] updated text on vpn page to bring buttons above the fold

- android/src/com/frostwire/android/gui/adapters/menu/AbstractDeleteFilesMenuAction.java
- android/src/com/frostwire/android/gui/adapters/menu/DeleteAdapterFilesMenuAction.java
- android/src/com/frostwire/android/gui/adapters/menu/DeleteFileMenuAction.java
- android/src/com/frostwire/android/gui/adapters/menu/DeleteSingleFileMenuAction.java
- android/src/com/frostwire/android/gui/adapters/menu/FileListAdapter.java
- android/src/com/frostwire/android/gui/fragments/ImageViewerFragment.java
- android/src/com/frostwire/android/gui/fragments/MyFilesFragment.java
Refactored DeleteFileMenuAction to work without an adapter
> [android] Images are now deleted from ImageViewer

- android/src/com/frostwire/android/core/Constants.java
updated Express VPN link from @kad3mlia
> [android] updated promo link for ExpressVPN

- desktop/src/com/limegroup/gnutella/gui/GUIMediator.java
- desktop/src/com/limegroup/gnutella/gui/LocalClientInfoFactoryImpl.java
- desktop/src/com/limegroup/gnutella/gui/SendFeedbackDialog.java
- desktop/src/com/limegroup/gnutella/gui/bugs/LocalAbstractInfo.java
- desktop/src/com/limegroup/gnutella/gui/bugs/LocalClientInfo.java
- desktop/src/com/limegroup/gnutella/gui/menu/HelpMenu.java
- desktop/src/com/limegroup/gnutella/settings/UISettings.java
- desktop/src/org/limewire/concurrent/ThreadExecutor.java
Issue #632 
- Includes Send Feedback Dialog 
- Cleanup and Refactors
> [desktop][issue-632] Send Feedback Dialog

- android/apollo/src/com/andrew/apollo/MusicPlaybackService.java
- REPEAT_ALL mode by default on playlists
> REPEAT_ALL mode by default on playlists

- android/apollo/res/layout/grid_base.xml
- android/apollo/res/values/strings.xml
- android/apollo/src/com/andrew/apollo/ui/fragments/profile/ApolloFragment.java
- android/apollo/src/com/andrew/apollo/ui/fragments/profile/PlaylistSongFragment.java
- android/src/com/frostwire/android/core/Constants.java
Fix empty message for playlist detailed view. #719
- Included message in strings.xml file. 
- onLoadFinished method in PlaylistSongFragment override to set custom message.
- Added URL in Constants.java
> [android] Fix empty message for playlist detailed view

- android/apollo/src/com/andrew/apollo/utils/MusicUtils.java
Now when a playlist is playing and more song are added to it, player queue it's updated with that information too. #720
> [android] Songs added to the current playing playlist are added to the player queue too

- android/apollo/src/com/andrew/apollo/IApolloService.aidl
- android/apollo/src/com/andrew/apollo/MusicPlaybackService.java
- android/apollo/src/com/andrew/apollo/utils/MusicUtils.java
- android/apollo/src/com/andrew/apollo/widgets/ShuffleButton.java
Removes the old logic to play in shuffle mode  and includes a new one much more simple. #13
> [android ] Remember randomly played songs

- android/apollo/src/com/andrew/apollo/MusicPlaybackService.java
- android/apollo/src/com/andrew/apollo/adapters/SongAdapter.java
- android/apollo/src/com/andrew/apollo/ui/fragments/QueueFragment.java
- android/apollo/src/com/andrew/apollo/ui/fragments/SongFragment.java
[android] Fix drag and drop issue in queue fragment   #727
> [android] Songs can be reordered in Queue Fragment

- android/apollo/src/com/andrew/apollo/ui/fragments/profile/PlaylistSongFragment.java
this was the only one missing in a context menu on appollo
> [android] added missing context menu icon

- android/gradle/wrapper/gradle-wrapper.properties
> [android] gradle 4.8.1

- android/res/layout/view_my_files_thumbnail_list_item.xml
Bug introduced by @marcelinkaaa, bug reported by @marcelinkaaa, and finally fixed by @marcelinkaaa ;)
> [android] fixed the character limit on the extra line in My Files #156

- android/src/com/frostwire/android/gui/MainApplication.java
- common/src/main/java/com/frostwire/bittorrent/BTContext.java
- common/src/main/java/com/frostwire/bittorrent/BTEngine.java
- desktop/src/com/limegroup/gnutella/gui/Initializer.java
- desktop/src/com/limegroup/gnutella/util/FrostWireUtils.java
In relationship to https://github.com/frostwire/frostwire/issues/786
> [all] torrent client fingerprint and user-agent support

- android/apollo/res/values-iw/strings.xml
> [android] Apollo Hebrew translation updated

- android/res/values-de/strings.xml
- android/res/values-es/strings.xml
- android/res/values-fr/strings.xml
- android/res/values-hi/strings.xml
- android/res/values/strings.xml
- android/res/xml/settings_search_engines.xml
- android/src/com/frostwire/android/core/ConfigurationDefaults.java
- android/src/com/frostwire/android/core/Constants.java
- android/src/com/frostwire/android/gui/SearchEngine.java
- common/src/main/java/com/frostwire/search/idope/IdopeSearchPerformer.java
- common/src/main/java/com/frostwire/search/idope/IdopeSearchResult.java
- desktop/src/com/limegroup/gnutella/gui/search/SearchEngine.java
- desktop/src/com/limegroup/gnutella/settings/SearchEnginesSettings.java
- desktop/src/test/java/com/frostwire/tests/IdopeSearchPerformerTest.java
Issue-885
Adding Idope.se support for both android and desktop
Also added IdopeSearchPerformerTest file and string translations
> [common] Adding Idope.se search support
