android/apollo/src/com/andrew/apollo/NotificationHelper.java
android/changelog.txt
android/src/com/frostwire/android/gui/services/EngineService.java

So the reason that the FrostWire notification icon looked like a nontransparent white ball is that starting in Android Lollipop all the icons in status bar are required to be white (although at times apps will hack this to use their colored version). And we were using our colored version without any modifications so that android was paining it white. 
I think Alden did that on purpose as it was causing some problems on lollipop, however now everything seems to be working fine after the recent updates to android app. Tested it on lollipop, marshmallow and api 16 emulator.

[android] updated notification frostwire icon

---

android/src/com/frostwire/android/gui/services/EngineService.java

@aldenml I couldn't replicate the issue with my phone. But I suppose when it happens it must be some sort of syncrhonization issue with the Service's onDestroy method.
My guess is that the process is killed before the Bittorrent session can finish it's `abort()` procedure.
Therefore I propose this patch to have that last thread sleep for one more second.
If not, maybe a better patch would be to somehow get a valid confirmation from the bittorrent session that it's actually been aborted all the way, and then we can continue to shutdown.

[android] Sleep 1 more second, make sure BTEngine is stopped.

---

common/src/main/java/com/frostwire/search/archiveorg/ArchiveorgItem.java
common/src/main/java/com/frostwire/search/archiveorg/ArchiveorgSearchPerformer.java

#10 Archive.org return 'subject' in two different types, in one case String, in another as Array. Field Subject not uses. so I just deleted it.
and seriously for this $ 15? generous reward for such job.

[common, desktop] fix #10

---

README.md

Removed a duplicate link to **frostwire-common** old repository.

Duplicate link removed

---

android/apollo/src/com/andrew/apollo/utils/PreferenceUtils.java

This works just fine if you want the Last Added to be the first tab when you open My Music for the first time. See my further comment on #51 if you think the Recent tab should be also a default page in My Music depending if you played one of your songs first without downloading.

[android] changed the default page to Last Added in My Music

---

android/src/com/frostwire/android/gui/NotificationUpdateDemon.java
android/src/com/frostwire/android/gui/activities/MainActivity.java
android/src/com/frostwire/android/gui/fragments/TransfersFragment.java
android/src/com/frostwire/android/gui/services/EngineService.java

Ups
continuation of #141 
sorry for making all that mess
Yes, this should reside inside service, but I think NUD has its place. EngineService is almost 400 lines. I'm even thinking about removing the whole updatePermanentStatusNotification(...) from the EngineService into the demon but IDK if there's a reason that it's there (nothing seems to call it). Any thoughts?

Android permanent notification deamon

---

desktop/src/com/frostwire/gui/tabs/TransfersTab.java

Larger, more readable transfer filter buttons and larger filter box (with the box the only thing I was not able to do is to center the text inside? Any ideas how to do it?)
The change came with no loss in vertical space between the search section and transfer section.

Desktop buttons

---

android/src/com/frostwire/android/offers/Offers.java

So I tested making a purchase with -store- flavor.
Uninstalled.
installed 'plus' flavor.
And I managed to see the product I bought when I queried Products.listEnabled().
On my previous commit I try to make sure that the support frostwire setting is turned off when a purchase is made in basic. But this should make sure that if that didn't happen, wether you're on basic or plus, adnetworks are kill-switched by having their "started" method return false and when their showInterstitialMethods are invoked they fail right away.
I do this on a separate thread because of the comment earlier on a fix you performed.
Just an idea, perhaps this can be done a lot better.

[android] abort adnetwork initialization if adremoval purchased

---

common/src/main/java/com/frostwire/search/SearchManager.java

Minor. Search Engine Name doesn't need to have the domain name

[Common] Minor. Typo.

---

android/apollo/res/values/dimens.xml
android/apollo/src/com/andrew/apollo/widgets/ProfileTabCarousel.java

Fixing tab carousel height calculations.  Removing unused carousel shadow references #236
Also fixing variable mixup (mTabShadowHeight and mTabDisplayLabelHeight)

[android] Fixing tab carousel height calculations. 

---

android/apollo/res/layout/list_base.xml
android/apollo/src/com/andrew/apollo/ui/fragments/profile/ApolloFragment.java

This will remove always visible scrollbar line on some lists (the fast scroll will be used only when there are many items in the list and it will disappear after scrolling, same as in search) 
#223

[android] make all scrollbars behave the same

---

android/apollo/src/com/andrew/apollo/NotificationHelper.java

#252 
This will allow the notification contents to be visible on lock screen when notification privacy is up. On my phone (S5 6.0.1) at least this has a side effect of the fact that the notification in notification area is now expanding (previously lots of ongoing notifications blocked that expansion)
so it affects #251

[android] Make control notification visible

---

android/apollo/src/com/andrew/apollo/widgets/ProfileTabCarousel.java

This fixes an issue reported by @marcelinkaaa in #263 but it doesn't solve the #263 
It was due to a function to update the alpha layer was being fired when there was horizontal scrolling but not before. Added update function to onMeasure(...), so that the image is always darkened.

[android] consistency in showing dark layer in ArtistAlbum screen

---

android/apollo/src/com/andrew/apollo/ui/fragments/profile/ArtistAlbumFragment.java

in ArtistlbumFragment to avoid NPE.
Not showing the header would be better, but that would result in even worse spaghetti or a rewrite of the whole fragment, view, and adapter.

[android] mute clicks on fake spacer header item in lists

---

android/res/drawable/ad_menu_item_background_filled.xml
android/res/layout/view_preference_button_action_2.xml
android/res/layout/view_preference_buy_ads_2.xml
android/res/layout/view_preference_checkbox_seeding_2.xml
android/res/values/dimens.xml
android/res/values/strings.xml
android/res/values/themes.xml
android/res/xml/settings_application.xml
android/src/com/frostwire/android/gui/views/preference/ButtonActionPreference.java
android/src/com/frostwire/android/gui/views/preference/CheckBoxSeedingPreference.java

@aldenml styling and adjustments to layouts are complete. I added proper colors to material theme (notice that there is no separate style for preference activity like before - less to maintain)
new layouts such as view_preference_button_action_2.xml - are added for later and will replace view_preference_button_action.xml we have currently - as this layout is active now with original settings activity. 
Next steps:
1. work on making preferences functional ( with @grzesiekrzaca ):
a) BitTorrent connection, Wifi networks only, Select Storage
@gubatron - remember talking over the new layouts in Denver? We wanted to replace 'Use 3G/4G for BitTorrent' for 'Wi-Fi Networks Only' where cloud downloads are included in the setting. 
Do you have any comments/pointers for me and @grzesiekrzaca ? 
b) …

[android] added styles and custom layouts to the new material settings

---

android/src/com/frostwire/android/gui/dialogs/AbstractConfirmListDialog.java
android/src/com/frostwire/android/gui/views/AbstractListAdapter.java

Related to #293 
So I needed an information for the adapter that the item check state was changed so that the logic of check all box could work. Due to the fact that we can check an item without using the check box but any part of the item (on that branch in check mode) it would be hard to find the checkbox without some .getParent() conga line. I really did not need the exact item because all I needed was the info that any item was passed, so I could have passed a null but that somehow did not seem clean. So I thought why not make the adapter return the item itself rather than a CompundButton with the item as a tag.

[android] make checked listener in abstract list adapter operate on items instead of views.

---

android/src/com/frostwire/android/gui/activities/SettingsActivity.java

This allows user if set to true to delete their onetime purchase after clicking it 20 times. Probably should be set to false.

[android] internal build variable (for consuming purchases) to false

---

android/res/layout/view_preference_category_material.xml
android/res/values-v17/themes.xml
android/res/values/themes.xml

@aldenml I know it is adding a new v-17 themes file - but it is the most straightforward solution I found to control the paddings of the list in preferences. Below are before screenshots from api17, 18,19. 
API 16 was good with only the layout. Let me know if we can keep it.

[android] fixed styling and padding on API 17-19

---

android/res/layout/dialog_preference_seekbar_with_checkbox.xml

Very small padding changes. Making the font for the displayed value larger. It was harder to read then it should. @gubatron

[android] adjustements to the seekbar preference layout font and padding

---

android/res/xml/settings_other.xml

this fixes crash introduced in 
https://github.com/frostwire/frostwire/commit/4ceac17a8e6bc5d21f0be5be3420bd2007b128bb
due to renaming of `ButtonActionPreference2` to `ButtonActionPreference`

[android] fix crash due to old class ref

---

android/res/values/styles.xml

Tiny change. The background was lost and it was white.

[android] added missing background color for the search progress

---

android/src/com/frostwire/android/gui/activities/MainActivity.java

This is not really needed and lead to a quite heavy Toolbar in new `BrowsePeerFragment` beeing reinflated multiple times when closing/opening the drawer.

[android] dont reinflate the fragment header when syncing the menu.

---

android/apollo/src/com/andrew/apollo/utils/NavUtils.java

Issue #357 : 
Just changed the call from ```startActivity``` to ```startActivityForResult``` method. 
The only guess that i have about this issue, it seems to be related to the integer value passed as expected value internally to ```startActivityForResult```.
I checked android ```Activity``` class, found ```startActivity``` calls ```startActivityForResult``` passing a ```-1``` as expected result but if that value is changed by ```0``` (I think we can use any integer) equalizer is showed with no problems
````
/**
* Launch a new activity.  You will not receive any information about when
* the activity exits.  This implementation overrides the base version,
* providing information about
* the activity performing the launch.  Because of this additional
* information, the {@link …
```

[android] Solving equalizer doesn't appear in player activity

---

android/res/layout/nav_view_header.xml
android/res/layout/toolbar_main.xml

After adding new toolbar, the drop down options changed its styling from light background to dark background, which we do not use throughout the app.

Minor styling adjustments for toolbar and nav

---

android/apollo/src/com/andrew/apollo/ui/fragments/RecentFragment.java

This fixes a problem @marcelinkaaa mentioned on slack - inconsistent way the layouts are shown for the "recent" tab in My Music.

[android] consistent layouts for recent tab

---

android/src/com/frostwire/android/offers/Offers.java
android/src/com/mopub/mobileads/AppLovinInterstitialAdapter.java

Instead of using MoPub through home made waterwall, we implement a MoPub custom adapter for AppLovin so that it can be configured on MoPub's dashboard.
AdNetworks were only initialized if they were on the list of active networks. Now we don't want to have AppLovin twice, however the network still needs to be initialized so that it can pre-cache ads on startup and actually work. Therefore we have a check on what networks are available on the home made waterwall.
If things change with MoPub, we can put our old AppLovin add with ease just by turning it back on.

[android] Mopub-Applovin adapter

---

android/res/layout/view_ad_menuitem.xml
android/res/menu/nav_view_menu.xml

Currently the navigation drawer ad is overlapping the menu, which causes the last menu item - "Exit" to be hidden under the ad itself. 
There is a few hacky ways to do it with layouts/paddings but they are a bit too much. This was the simplest way to accomplish it. 
I am not sure how to do it any other way. If you have any pointers I will be happy to give them a go.

[android] fix for ad-view overlaying on top of the menu

---

android/res/layout/view_preference_search_engine.xml
android/res/values/dimens.xml

android:paddingLeft in the top layout was not working properly on API 16-19 - had to apply padding on its children instead

[android] fixed settings-search engines padding

---

desktop/src/com/limegroup/gnutella/gui/LanguageWindow.java

This is a minor issue when trying to change the Language from the 'flag' icon at the bottom bar, the Language-Window has a link 'Help to translate FrostWire' that was pointing the old frostwire-desktop repo. I didn't open an issue because is a tiny thing.

Fixes broken link on Language change

---

android/res/menu/player_add_to_homescreen.xml
android/res/menu/player_favorite.xml
android/res/menu/player_search.xml

Test case: 
1. My Music -> 2. Albums (check what icon appear on the toolbar and what appears on overflow menu) -> 3. click on search icon (check what icon appear on the toolbar and check what appears on overflow menu)
When you click on search icon - you can see 'Add to favorites' twice - once in the toolbar as an icon and then in the overflow menu. Also you are already in the search mode - yet you still see 'search' as an option in the overflow menu, which does not do anything other then returning you to the same screen. By changing app:showAsAction="ifRoom" to app:showAsAction="always” I only show the icons in the toolbar without the repetition. This will, however, force the favorites icon to be in the toolbar (and not only in the overflow menu) on smaller screen devices - I have tested …

[android] overflow menu fix in apollo

---

android/AndroidManifest.xml
android/res/xml/provider_paths.xml
android/src/com/frostwire/android/gui/util/UIUtils.java

It seems that after SDK 24 we cannot pass a file:// URI to another app via Intent data
since all the permissions to interact with such file are a responsability of our app
android now decided we need to have a content provider for the files we send to other intents
This is working so far for our default save location, but it's problematic when the user
changes the default save location to say an external storage device since the FileProvider
documentation says that we must provide the directories before-hand when we declare
the provider in the manifest.
it is my hope that we'll find a way to manipulate such paths programatically somehow. Perhaps
you've read about this already @aldenml

[android] Fixes file opening issues for default storage

---

android/src/com/frostwire/android/gui/activities/PreviewPlayerActivity.java

@gubatron I am expanding the horizontal preview to the width of the screen when no ads on the right side are being loaded, or a user paid for the no-ad version. 
Of course that can be later modified if you set up the logic to fill in our own placement ads. 
Let me know if it works ok for now. Looks good on my devices.

[android] expand horizontal preview view when no ads are displayed

---

android/res/layout/toolbar_main.xml

Toolbar heigh changes slightly depending on the devices and portrait/horizontal modes. We kept it set at 54dp, which is good but since the height was not adjusting when switched to horizontal mode the toolbar title was not properly aligned with the icons. As shown on the image (nr.1 is what we have, nr.2 is with adjusted height of the toolbar
)

[android] fixes sizing differences in portrait and landscape mode

---

android/src/com/frostwire/android/gui/activities/PreviewPlayerActivity.java

@gubatron This removes and restores the status bar in video preview. With status bar visible it was not fully full screen, and it was bugging me a bit :) 
Now while adding it I discovered another bug that was already there. When you enter video preview and tap on the image of full screen icon before the video starts loading (right away) - the full screen layout is a bit odd (the download button is visible, and sometimes even the ad shows on top).

[android] removes status bar on full screen video preview

---

android/res/values/colors.xml

browse peer thumbnail was set to same color as selected background, thus blending together in selection mode

[android] changed color of browse peer thumbnail

---

android/res/layout/fragment_transfers.xml
android/res/layout/view_clearable_edittext.xml
android/res/layout/view_searchinput.xml
android/res/values/colors.xml
android/res/values/styles.xml

Design update of the transfer screen 'add magnet' field, slight update to the view_clearable_edittext.xml and some code cleanup. 
Also - ‘maxLines = 1’, not wroking correctly as of sdk 25. It replaces deprecated ‘singleLine’ but with a current bug its not working correctly withouth ‘inputType’ being added. Being looked at by android developers.

Search view design update

---

android/res/layout-land/view_searchinput_tablayout.xml
android/res/layout-land/view_searchinput_tablayout_custom_tab.xml

preserving vertical space on small devices.
@gubatron should work well now, but that separate horizontal layout for TabLayout was necessary to set the height properly

[android] added custom horizontal layout for Tabs in Search

---

android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java
android/src/com/frostwire/android/gui/fragments/TransfersFragment.java

Before the overflow menu icon on the toolbar of the transfer screen would only refresh (after clearing all the transfer list items) upon tapping on the menu, or when going to navigation and back, but not while the user stays on the screen and clears the list. 
Therefore the overflow menu icon would stay visible with empty list. 
Added refresh so that the icon updates as the user deletes/clears the transfer list. 
Huge thanks @gubatron

[android] refreshes transfer menu on ‘clearing’ transfer list

---

android/src/com/frostwire/android/gui/fragments/SearchFragment.java

Before when adding magnet/torrent/youtube from a transfer screen you would go automatically to search page. The search bar would contain words that you looked for but it was shown as a hint - therefore no 'x' button to cancel search if it took too long, and upon changing tabs underneath the hint would disappear so the user would not see the search term he/she looked for in the bar anymore. 
Changing the search input from hint to a text makes the text stay in the bar even if tabs are changed and 'x' added for easy exit.

[android] changed add magnet search from a hint to a text

---

android/res/layout/view_drawer_search_filters.xml

Because of the added margin - small screens were pushing content to new line pic.1. Rearranged the layout so that does not happen as on pic.2.

[android] fixed filter tip set up for small devices

---

android/res/layout/view_menu_list_item.xml
android/res/layout/view_social_buttons.xml

in [android] adjustements and layout cleanup in view_social_buttons - Because the wizard is now also in horizontal mode so is the view_social_buttons.xml. Not being in scroll view - some text and social media icons were cut off. 
Also different screen sized devices showed the check icon differently, like on the image below. Adjusted and tested on multiple screens.

Layout cleanup updates

---

android/res/drawable/keyword_tag_filter_tip_add.xml
android/res/drawable/keyword_tag_filter_tip_minus.xml
android/res/layout/view_drawer_search_filters.xml
android/res/values/styles.xml

Alden, in your commit "[android] using layer list drawable for KeywordTagView add/minus" you removed the plus and minus drawables, which I understand the reason for. The white drawable background that was used under the tip tags + and - sign was also removed, hence they became invisible. 
I added the signs the same way you added them for the regular active filter tags. Hope it looks ok.

added missing include and exclude images into the tip tag

---

android/src/com/frostwire/android/gui/fragments/BrowsePeerFragment.java

Before even when there was 0 files - a user could still enter selection mode in My Files. Also the check when a user is in My Files -> Filter.

[android] hides selection checkbox when there is no files on the list, in My Files and My Files -> Filter

---

android/res/layout/fragment_transfers.xml

The notification was not showing right on all the tabs in transfer fragment. It would stop showing on tabs where the list view was visible - the download list was shown - and would show on pages with no download present; as completed tab when no downloads were completed.

[android] moved rich sd card notification

---

android/res/layout/fragment_transfers.xml

The ScrollView applied to TransfersNoSeedsView so that a user can see a full message on horizontal views was placed last in the RelativeLayout, which means it displayed first covering other views. Because of that a user would not be able to click on any download to see the context menu or see its files as the scrollview was on top.

[android] RelativeLayout positioning fix

---

android/src/com/frostwire/android/gui/fragments/ImageViewerFragment.java

Issue #585: @gubatron yes it meant to open an image in the external image viewer in case a user want to easily go and edit an image or further apply some fun filters we of course wont have as a downloader app. 
But it only should leave the app when in fullScreenMode. Hence the added code. 
As of now when we select one image - and are in selection more - we can use the Open Menu Action to view that selected image in full screen mode within FrostWire.

[android] Open Menu Action to open image with external Image Viewer

---

android/res/layout/view_search_progress.xml

On smaller screens and depending on other currently present notifications on the page, the “No results were found” notification would often go outside of the page. Made it scrollable so that the Retry button is always accessible.

[android] added scroll view to view_search_progress

---

android/apollo/res/values/strings.xml
android/apollo/src/com/andrew/apollo/loaders/LastAddedLoader.java
android/apollo/src/com/andrew/apollo/ui/fragments/LastAddedFragment.java
android/apollo/src/com/andrew/apollo/ui/fragments/RecentFragment.java
android/apollo/src/com/andrew/apollo/ui/fragments/profile/ApolloFragment.java
android/apollo/src/com/andrew/apollo/ui/fragments/profile/LastAddedFragment.java

This pull request is intended to add default strings when fragments are empty correctly.
The idea is basically add to ApolloFragment a method called `getEmptyStringId()` that will return the default string id `R.string.empty_music`. 
Then that method will be overriden by subclasses of ApolloFragment such as `RecentFragment` or `LastAddedFragment` for example.

[WIP] Setting up correclty strings to empty fragments

---

android/apollo/src/com/andrew/apollo/ui/fragments/SongFragment.java

Changing itemsOffset parameter in SongFragment to avoid blank row creating at the end of the list.

[android] Changing itemsOffset parameter in SongFragment 

---

desktop/src/com/frostwire/gui/components/transfers/TransferDetailFilesDataLine.java
desktop/src/com/frostwire/gui/components/transfers/TransferDetailGeneral.java

If you can take a look @gubatron  - Small adjustments in spacing and layout of the general tab. I think its a bit cleaner to read through all the information. Let me know what you think. 
This one is before pic: 
This one is after:

[desktop] readjusted spacing and layout in TransferDetailGeneral

---

android/res/layout/fragment_about.xml
android/src/com/frostwire/android/gui/fragments/AboutFragment.java

@gubatron Noticed that you merged without the check. Added hiding the support button (and the divider that followed it) when on FW Basic.

[android] made the support button not show on FW Basic

---

android/AndroidManifest.xml
android/src/com/frostwire/android/gui/activities/MainActivity.java
android/src/com/frostwire/android/gui/services/Engine.java
android/src/com/frostwire/android/gui/services/EngineService.java
android/src/com/frostwire/android/gui/transfers/TransferManager.java
android/src/com/frostwire/android/gui/util/DangerousPermissionsChecker.java
android/src/com/frostwire/android/offers/MoPubAdNetwork.java
android/src/com/frostwire/android/offers/Offers.java

@aldenml @muckachina please take a look at this and test this branch.
The purpose of this branch is to perform a passive shutdown of FrostWire, in the past we tried to force kill all services and the process which is against Android's nature, which will try to revive the process anyway.
It's working as expected, at least what I've tested:
1. That ad networks aren't shutdown and they continue to work, both banners and interstitials. Had to perform a reflection hack on a MoPubInterstitial class to reload interstitials that were destroyed upon exit.
2. HTTP and Image loading works after restart
3. Bittorrent transfers work after restart
4. Previous BitTorrent transfers are restored to their previous stage, however, there's a hiccup on which you will see previous transfers in "Error" state …

[android] Shutdown logic revision

---

android/AndroidManifest.xml
android/src/com/frostwire/android/gui/activities/MainActivity.java
android/src/com/frostwire/android/gui/fragments/TransfersFragment.java
android/src/com/frostwire/android/gui/services/Engine.java
android/src/com/frostwire/android/gui/services/EngineService.java
android/src/com/frostwire/android/gui/transfers/TransferManager.java
android/src/com/frostwire/android/gui/transfers/UIBittorrentDownload.java
android/src/com/frostwire/android/gui/util/DangerousPermissionsChecker.java
android/src/com/frostwire/android/offers/MoPubAdNetwork.java
android/src/com/frostwire/android/offers/Offers.java
common/src/main/java/com/frostwire/bittorrent/BTEngine.java

@aldenml @muckachina please take a look at this and test this branch.
The purpose of this branch is to perform a passive shutdown of FrostWire, in the past we tried to force kill all services and the process which is against Android's nature, which will try to revive the process anyway.
It's working as expected, at least what I've tested:
That ad networks aren't shutdown and they continue to work, both banners and interstitials. Had to perform a reflection hack on a MoPubInterstitial class to reload interstitials that were destroyed upon exit.
HTTP and Image loading works after restart
Bittorrent transfers work after restart
Previous BitTorrent transfers are restored to their previous stage, however, there's a hiccup on which you will see previous transfers in "Error" state for a second, …

[android] Shutdown logic fix

---

android/src/com/frostwire/android/gui/fragments/TransfersFragment.java

@gubatron it looks like it just was not called from onResume, only on initComponents. Adding to onResume did the trick for me.

[android] adding initStorageRelatedRichNotifications in onResume

---

common/src/main/java/com/frostwire/search/torrentz2/Torrentz2SearchPerformer.java
common/src/main/java/com/frostwire/search/torrentz2/Torrentz2SearchResult.java

Fixing torrentz2 search age (i.e. creationTime). Previously torrentz2 do not show the creationTime (age of torrent file) in the app.
- **Fixed the REGEX pattern** to extract the Date (in **Torrentz2SearchPerformer**)
[earlier "\<span\>" tag was concatenated along with the Date] So, i fixed that issue.
- Optimized and fixed the **parsing of creationTime** (in **Torrentz2SearchResult**)

Fixed Torrentz2 age (i.e. creationTime)

---

android/res/values-de/strings.xml
android/res/values-es/strings.xml
android/res/values-fr/strings.xml
android/res/values-hi/strings.xml
android/res/values/strings.xml
android/res/xml/settings_search_engines.xml
android/src/com/frostwire/android/core/Constants.java
android/src/com/frostwire/android/gui/SearchEngine.java
common/src/main/java/com/frostwire/search/one337x/One337xSearchPerformer.java
common/src/main/java/com/frostwire/search/one337x/One337xSearchResult.java
common/src/main/java/com/frostwire/search/one337x/One337xTempSearchResult.java
desktop/src/com/limegroup/gnutella/gui/search/SearchEngine.java
desktop/src/com/limegroup/gnutella/settings/SearchEnginesSettings.java
desktop/src/test/java/com/frostwire/tests/One337xSearchPerformerTest.java

Add a **popular torrent search** - [**1337x**](https://1337x.gd) to the search engine in the android app.
Replicated "yify" search package,  modified a little and added 1337x search support.
Added 3 files in **one337x package** in search:
- One337xSearchPerformer.java
- One337xSearchResult.java
- One337xTempSearchResult.java
Modified 4 files:
- SearchEngine.java
- Constants.java
- settings_search_engines.xml
- strings.xml
works perfectly in MIUI11, android 7.1.1, android 9
My first contribution on GITHUB. Hope you would love it 😄  and 1337x ❤️ .

[common] Added 1337x torrent search support

---

common/src/main/java/com/frostwire/bittorrent/BTEngine.java

When using return, if a file or folder was manually deleted, all
remaining torrents in the loop were skipped.

[common] Use continue instead of return if setupSaveDir() returns null

---

android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties

Small clean up of gradle config files in the Android project. 
I removed properties under `gradle-wrapper.properties` that are not relevant to that scope and that should only be declared in the root `gradle.properties` of the project. 
I also disabled the Jetifier option because it is no longer needed for this project. Enabling Jetifier was required only in the distant past for projects that used legacy libraries that have not been migrated to use AndroidX. Enabling Jetifier means slower build speeds, thus I disabled it.

Clean up Android Gradle config files

---

common/dependencies.gradle
desktop/build.gradle

This is a quick PR that upgrades a few dependencies to their latest versions across both common and desktop. The following dependencies have been upgraded to the following versions:
- Update org.jetbrains.annotations to 26.0.2
- Update com.google.re2j to 1.8
- Update com.google.gson to 2.13.2
- Update com.squareup.okhttp3 to 4.12.0
- Update org.xerial:sqlite-jdbc to 3.50.3.0
Food for thought: maybe deduplicate dependencies across the Android and desktop versions. I'm not sure how well that may work out, but I might attempt it soon.

[common/desktop] Update dependencies
